import { DemoData, NavItem } from "./types";

export const NAV_ITEMS: NavItem[] = [
  { label: "Dashboard", icon: "dashboard", section: "MAIN" },
  { label: "Manage Demo", icon: "manageDemo", section: "DATA" },
  { label: "Build Demo", icon: "buildDemo", section: "DATA" },
  { label: "Upload Demo", icon: "uploadDemo", section: "DATA" },
  { label: "Manage Team", icon: "manageTeam", section: "DATA" },
  { label: "Contacts Informal", icon: "contacts", section: "DATA" },
  { label: "Invoices Balances", icon: "documentDemo", section: "DATA" },
  { label: "Products", icon: "products", section: "PAGES" },
  { label: "Profile Form", icon: "profile", section: "PAGES" },
  { label: "Task", icon: "task", section: "PAGES" },
  { label: "Calendar", icon: "calendar", section: "PAGES" },
  { label: "FAQ Page", icon: "faq", section: "PAGES" },
  { label: "Compress", icon: "compress", section: "DESIGN" },
  { label: "Document", icon: "documentDemo", section: "PAGES" },
  { label: "Bar Chart", icon: "barChart", section: "CHARTS" },
];

export const MOCK_DATA: DemoData[] = [
  {
    id: 1,
    year: 2019,
    month: 1,
    brand: "carrier-junior",
    host: "demo",
    view: "",
    format: "firstview",
    flight: null,
  },
  {
    id: 2,
    year: 2019,
    month: 1,
    brand: "carrier-junior",
    host: "demo",
    view: "",
    format: "firstview",
    flight: null,
  },
  {
    id: 3,
    year: 2019,
    month: 1,
    brand: "carrier-junior",
    host: "demo",
    view: "",
    format: "firstview",
    flight: null,
  },
  {
    id: 4,
    year: 2019,
    month: 1,
    brand: "carrier-junior",
    host: "demo",
    view: "",
    format: "firstview",
    flight: null,
  },
  {
    id: 5,
    year: 2019,
    month: 1,
    brand: "carrier-junior",
    host: "demo",
    view: "",
    format: "inpage",
    flight: null,
  },
  {
    id: 6,
    year: 2019,
    month: 1,
    brand: "carrier-junior",
    host: "demo",
    view: "",
    format: "inpage",
    flight: null,
  },
  {
    id: 7,
    year: 2019,
    month: 1,
    brand: "carrier-junior",
    host: "demo",
    view: "",
    format: "inpage",
    flight: null,
  },
  {
    id: 8,
    year: 2019,
    month: 1,
    brand: "carrier-junior",
    host: "demo",
    view: "",
    format: "inpage",
    flight: null,
  },
  {
    id: 9,
    year: 2019,
    month: 1,
    brand: "carrier-junior",
    host: "demo",
    view: "",
    format: "inpage",
    flight: null,
  },
  {
    id: 10,
    year: 2019,
    month: 1,
    brand: "carrier-junior",
    host: "demo",
    view: "",
    format: "inpage",
    flight: null,
  },
  {
    id: 11,
    year: 2020,
    month: 2,
    brand: "tech-innovate",
    host: "prod",
    view: "",
    format: "firstview",
    flight: "FL-123",
  },
  {
    id: 12,
    year: 2020,
    month: 3,
    brand: "creative-sol",
    host: "stage",
    view: "",
    format: "inpage",
    flight: "FL-456",
  },
  {
    id: 13,
    year: 2021,
    month: 5,
    brand: "carrier-junior",
    host: "demo",
    view: "",
    format: "firstview",
    flight: null,
  },
  {
    id: 14,
    year: 2022,
    month: 8,
    brand: "alpha-brand",
    host: "demo",
    view: "",
    format: "inpage",
    flight: "FL-789",
  },
  {
    id: 15,
    year: 2023,
    month: 11,
    brand: "global-net",
    host: "prod",
    view: "",
    format: "firstview",
    flight: "FL-101",
  },
];
