FROM node:18-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

ENV NODE_ENV=development
ENV CHOKIDAR_USEPOLLING=true
ENV NEXT_WEBPACK_USEPOLLING=1
ENV WATCHPACK_POLLING=true

EXPOSE 3000

CMD ["npm", "run", "dev"]
