# Dành cho development (hot reload)
FROM node:18-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

# Dùng port 3000
EXPOSE 3000

# Bật hot reload
ENV CHOKIDAR_USEPOLLING=true

CMD ["npm", "run", "dev"]
